skip-check:
  # Image digest checks - acceptable in development environments
  # For production, consider using image digests instead of tags
  - CKV_K8S_43  # Image should use digest
  - CKV_K8S_14  # Image Tag should be fixed - not latest or blank

  # Secrets as environment variables - acceptable for non-sensitive config
  # Database credentials are properly stored in secrets
  - CKV_K8S_35  # Prefer using secrets as files over secrets as environment variables

  # Read-only filesystem - databases require writable directories
  # PostgreSQL and Redis need to write to data directories, logs, etc.
  - CKV_K8S_22  # Use read-only filesystem for containers where possible

# These checks are skipped because:
# - CKV_K8S_43: Using image tags (myapp:websocket-fix) instead of SHA digests
#   This is acceptable in development/testing environments for easier deployment
# - CKV_K8S_14: Using specific tags instead of digest
#   Same rationale as above
# - CKV_K8S_35: Using environment variables for configuration
#   Non-sensitive configuration is loaded from ConfigMap as env vars
#   Sensitive data (passwords, keys) are properly stored in secrets
# - CKV_K8S_22: Read-only filesystem for databases
#   PostgreSQL and Redis require write access to data directories, logs, sockets
#   These are properly isolated using volume mounts and security contexts
