apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-config
  namespace: myapp
data:
  ENVIRONMENT: "production"
  DEBUG: "False"
  ALLOWED_HOSTS: "myapp.example.com,www.myapp.example.com"
  CORS_ALLOWED_ORIGINS: "https://myapp.example.com,https://www.myapp.example.com"
  CSRF_TRUSTED_ORIGINS: "https://myapp.example.com,https://www.myapp.example.com"
