apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: myapp-prod

resources:
  - ../base
  - configmap.yaml
  - secret.yaml
  - hpa.yaml

patchesStrategicMerge:
  - deployment-patch.yaml
  - service-patch.yaml
  - ingress-patch.yaml

replicas:
  - name: myapp
    count: 3

images:
  - name: myapp
    newTag: v1.0.0
