apiVersion: v1
kind: Secret
metadata:
  name: myapp-secret
  namespace: myapp
type: Opaque
stringData:
  # pragma: allowlist nextline secret
  SECRET_KEY: "your-production-secret-key-here-change-this"
  # pragma: allowlist nextline secret
  DATABASE_URL: "postgres://myapp:strongpassword@postgres-prod:5432/myapp_prod"
