name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  sast:
    uses: hijacksecurity/SecurityAsAService/templates/sast.yml@main
    secrets: inherit

  sca:
    uses: hijacksecurity/SecurityAsAService/templates/sca.yml@main
    secrets: inherit