name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  security-events: write
  contents: read
  checks: write
  pull-requests: write

jobs:
  sast:
    uses: hijacksecurity/SecurityAsAService/.github/workflows/sast.yml@main

  sca:
    uses: hijacksecurity/SecurityAsAService/.github/workflows/sca.yml@main
    secrets: inherit